name: qt-server-portable
region: nyc
services:
  - name: qt-backend
    dockerfile_path: Dockerfile
    github:
      branch: main
      repo: your-username/your-repo-name
    instance_size_slug: basic-xxs
    http_port: 8080

    # FIX: Explicitly tell the container to use 8080
    envs:
      - key: PORT
        value: "8080"

    routes:
      - path: /