# This is just a config file for DigitalOcean to know how to run the server.
# I don't really understand it all that much, but it works.

name: smvcar-server
region: nyc
services:
  - name: smvcar-server
    dockerfile_path: Dockerfile
    github:
      branch: main
      repo: Tallis-Larsen/smvcar-server
    instance_size_slug: basic-xxs
    http_port: 8080
    envs:
      - key: PORT
        value: "8080"
        scope: RUN_TIME
        type: GENERAL
    health_check:
      http_path: /
      initial_delay_seconds: 20
    routes:
      - path: /
        preserve_path_prefix: false