name: qt-server-portable
region: nyc
services:
  - name: qt-backend
    type: web                    # Add this explicitly
    dockerfile_path: Dockerfile
    source_dir: /                # Add this
    github:
      branch: main
      repo: your-username/your-repo-name
    instance_size_slug: basic-xxs
    http_port: 8080
    run_command: ./server        # Add this explicitly
    envs:
      - key: PORT
        value: "8080"
        scope: RUN_TIME
        type: GENERAL
    health_check:
      http_path: /               # Add this
      initial_delay_seconds: 10
      period_seconds: 10
    routes:
      - path: /